import type { Metadata } from "next";
import localFont from "next/font/local";
import styles from "./layout.module.scss";
import "./globals.css";
import Menu from "@/components/Menu/Menu";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className={styles.container}>
          {/* チェックボックスによるメニュー制御（非表示） */}
          <input 
            type="checkbox" 
            id="menu-toggle" 
            className={styles.menuCheckbox} 
            defaultChecked={true}
          />

          <div className={styles.page}>
            {children}
          </div>

          {/* ハンバーガーメニューボタン - モバイル向け */}
          <label 
            htmlFor="menu-toggle" 
            className={styles.hamburgerButton}
            aria-label="メニューを開閉する"
          >
            ☰
          </label>

          {/* メニューコンテナ */}
          <div
            id="navigation-menu"
            className={styles.Sidebar}
            role="navigation"
          >
            <div className={styles.PaperContainer}>
              <div className={styles.Menu}>
                <Menu />
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
