import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import MenuWrapper from "@/components/MenuWrapper/MenuWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body >
        <MenuWrapper>
          {children}
        </MenuWrapper>
      </body>
    </html>
  );
}